# See: https://docs.github.com/en/actions/sharing-automations/reusing-workflows
# See: https://github.com/asimov-specs/.github/blob/master/.github/workflows/tweet-release.yaml
---
name: Tweet release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: asimov-specs/.github/.github/workflows/tweet.yaml@master
    with:
      message: |
        📦 ${{ github.event.repository.name }} ${{ github.event.release.tag_name }} has been released:
        ${{ github.event.release.html_url }}
    secrets: inherit
